### ISSUE TITLE
Errors during compute node installation: Service may have incorrect IPFilter configuration

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-factory#2]
During compute node installation following errors appear at the end of the installation process:
```
Service may have incorrect IPFilter configuration
```
This may be related to `reload_smf_manifests()` in computenode.sh

Estimated time: 8h

**Comment by ghost** [comment]
This is known bug in illumos.

**Comment by ghost** [comment]
The most apropriate way is to supress logging of error messages to system consoles and keep them only in log files. The message "Service may have incorrect IPFilter configuration" is not caused by actual error, it's caused by the way the system boots and starts.

Edit: This is caused by https://smartos.org/bugview/OS-4332 with fix on http://us-east.manta.joyent.com/jmc/public/webrev/OS-4332/usr/src/cmd/ipf/svc/ipfd.c.udiff.html

Next steps:
    [ ] Incorporate the diff
    [ ] build testing platform image
    [ ] build testing computenode image
    [ ] install using the image just built

**Comment by dn0** [comment]
@jurajlutter Disabling logging seems like a nasty workaround. Lets keep this as a last resort. And search for a better solution/workaround.

Since the `svc:/system/manifest-import` does lots of things (including `svccfg import -p /dev/msglog`), I suggest that we import the `/opt/custom/smf` manifests manually and remove the `svc:/system/manifest-import` command.

(reference: https://smartos.org/bugview/OS-4332)

**Comment by ghost** [comment]
Yes, I've applied proposed fix and will test it.
